<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="42277" started-at="2012-08-09T12:37:38Z" finished-at="2012-08-09T12:38:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="42277" started-at="2012-08-09T12:37:38Z" finished-at="2012-08-09T12:38:20Z">
      <class name="com.exit.tests.Administrator">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="setUp" is-config="true" duration-ms="5577" started-at="2012-08-09T16:37:38Z" finished-at="2012-08-09T16:37:43Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="setUp" is-config="true" duration-ms="7" started-at="2012-08-09T16:37:43Z" finished-at="2012-08-09T16:37:43Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testRestorPassTrue(java.lang.String)[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="testRestorPassTrue" duration-ms="18026" started-at="2012-08-09T16:37:43Z" data-provider="restorPassTrue" finished-at="2012-08-09T16:38:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[100102]]>
              </value>
            </param>
          </params>
          <exception class="com.thoughtworks.selenium.SeleniumException">
            <message>
              <![CDATA[ERROR: Element link=https://r.mail.yandex.net/url/yFGeiXrIhqkBih3ZxxiHWQ,1344509935/umagicpro-pp%2Fuser%2Freset%2F463%2F1344333893%2F90c767fb58489d0d193f05635371045a not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Element link=https://r.mail.yandex.net/url/yFGeiXrIhqkBih3ZxxiHWQ,1344509935/umagicpro-pp%2Fuser%2Freset%2F463%2F1344333893%2F90c767fb58489d0d193f05635371045a not found
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.click(DefaultSelenium.java:193)
	at com.exit.tests.Administrator.testRestorPassTrue(Administrator.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- com.thoughtworks.selenium.SeleniumException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRestorPassTrue -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="tearDown" is-config="true" duration-ms="664" started-at="2012-08-09T16:38:01Z" finished-at="2012-08-09T16:38:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="setUp" is-config="true" duration-ms="5706" started-at="2012-08-09T16:38:02Z" finished-at="2012-08-09T16:38:08Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testRestorPassTrue(java.lang.String)[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="testRestorPassTrue" duration-ms="11761" started-at="2012-08-09T16:38:08Z" data-provider="restorPassTrue" finished-at="2012-08-09T16:38:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[SqaTest@yandex.ru]]>
              </value>
            </param>
          </params>
          <exception class="com.thoughtworks.selenium.SeleniumException">
            <message>
              <![CDATA[ERROR: Element link=https://r.mail.yandex.net/url/yFGeiXrIhqkBih3ZxxiHWQ,1344509935/umagicpro-pp%2Fuser%2Freset%2F463%2F1344333893%2F90c767fb58489d0d193f05635371045a not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Element link=https://r.mail.yandex.net/url/yFGeiXrIhqkBih3ZxxiHWQ,1344509935/umagicpro-pp%2Fuser%2Freset%2F463%2F1344333893%2F90c767fb58489d0d193f05635371045a not found
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.click(DefaultSelenium.java:193)
	at com.exit.tests.Administrator.testRestorPassTrue(Administrator.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- com.thoughtworks.selenium.SeleniumException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRestorPassTrue -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="tearDown" is-config="true" duration-ms="390" started-at="2012-08-09T16:38:20Z" finished-at="2012-08-09T16:38:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="tearDown" is-config="true" duration-ms="0" started-at="2012-08-09T16:38:20Z" finished-at="2012-08-09T16:38:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.exit.tests.Administrator -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
