<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="41302" started-at="2012-08-09T10:55:23Z" finished-at="2012-08-09T10:56:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="41302" started-at="2012-08-09T10:55:23Z" finished-at="2012-08-09T10:56:04Z">
      <class name="com.exit.tests.Administrator">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="setUp" is-config="true" duration-ms="6145" started-at="2012-08-09T14:55:23Z" finished-at="2012-08-09T14:55:29Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="setUp" is-config="true" duration-ms="8" started-at="2012-08-09T14:55:29Z" finished-at="2012-08-09T14:55:29Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testRestorPassTrue(java.lang.String)[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="testRestorPassTrue" duration-ms="18115" started-at="2012-08-09T14:55:29Z" data-provider="restorPassTrue" finished-at="2012-08-09T14:55:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[100102]]>
              </value>
            </param>
          </params>
          <exception class="com.thoughtworks.selenium.SeleniumException">
            <message>
              <![CDATA[ERROR: Element //html[@id='js']/body/div/div[2]/div[4]/div[2]/div[2]/div/div[3]/div/div/div[4]/div[2]/div/div/table/tr/td/div/div/div/div/div/div[2]/table/tbody/tr[6]/td/div/p[2] not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Element //html[@id='js']/body/div/div[2]/div[4]/div[2]/div[2]/div/div[3]/div/div/div[4]/div[2]/div/div/table/tr/td/div/div/div/div/div/div[2]/table/tbody/tr[6]/td/div/p[2] not found
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.click(DefaultSelenium.java:193)
	at com.exit.tests.Administrator.testRestorPassTrue(Administrator.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- com.thoughtworks.selenium.SeleniumException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRestorPassTrue -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="tearDown" is-config="true" duration-ms="3130" started-at="2012-08-09T14:55:47Z" finished-at="2012-08-09T14:55:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="setUp" is-config="true" duration-ms="5454" started-at="2012-08-09T14:55:50Z" finished-at="2012-08-09T14:55:56Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testRestorPassTrue(java.lang.String)[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="testRestorPassTrue" duration-ms="8120" started-at="2012-08-09T14:55:56Z" data-provider="restorPassTrue" finished-at="2012-08-09T14:56:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[SqaTest@yandex.ru]]>
              </value>
            </param>
          </params>
          <exception class="com.thoughtworks.selenium.SeleniumException">
            <message>
              <![CDATA[ERROR: Element //html[@id='js']/body/div/div[2]/div[4]/div[2]/div[2]/div/div[3]/div/div/div[4]/div[2]/div/div/table/tr/td/div/div/div/div/div/div[2]/table/tbody/tr[6]/td/div/p[2] not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Element //html[@id='js']/body/div/div[2]/div[4]/div[2]/div[2]/div/div[3]/div/div/div[4]/div[2]/div/div/table/tr/td/div/div/div/div/div/div[2]/table/tbody/tr[6]/td/div/p[2] not found
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.click(DefaultSelenium.java:193)
	at com.exit.tests.Administrator.testRestorPassTrue(Administrator.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- com.thoughtworks.selenium.SeleniumException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRestorPassTrue -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="tearDown" is-config="true" duration-ms="308" started-at="2012-08-09T14:56:04Z" finished-at="2012-08-09T14:56:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.exit.tests.Administrator@66e64686]" name="tearDown" is-config="true" duration-ms="1" started-at="2012-08-09T14:56:04Z" finished-at="2012-08-09T14:56:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.exit.tests.Administrator -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
